---
layout: cv
title: Jacob Jewett's CV
---
# Jacob Jewett
Bachelor of Science in Accounting
<div id="webaddress">
<a href="www.linkedin.com/in/jacobgjewett">www.linkedin.com/in/jacobgjewett</a>
</div>


## Education

`July 2024`
__Bachelor of Science in Accounting__
_Brigham Young University–Idaho_

-	GPA: 3.63
-	Major GPA: 3.66 
-   Student Accounting Society Mentorship Officer   

## Experience

`April 2023-Current`
__Accounting Specialist__
_City of Rexburg_

-   Wrote VBA programs saving as much as 15-20 minutes on many recurring reports
-   Improved general journal entry redundancy by developing journal import functionality
-   Aided in the transition from internal reports to Power BI developing valuable reports

`June 2023-Current`
__Co-Owner__
_South Fork Fly Rods LLC_
-   Created and manage detailed excel general ledger and reconciliation process
-   Developed detailed production process to ensure product quality

`April 2022-April 2023`
__Tutor-Intermediate Financial Accounting I__
_Brigham Young University-Idaho_
-   Built students’ confidence through one-on-one target focused appointments, resulting in increased test scores
-   Identified students individual learning methods to tailor sessions to their needs
-   Focused on comprehension through various teaching and retention methods

`January 2022-April 2022`
__Assurance Intern__
_WSRP LLC_
-   Gained understanding and technical experience with Excel and other audit programs
-   Regularly drafted financial statements and letters to management 
-   Worked effectively in small team settings to audit companies with up to $45 million in revenue

## Leadership & Service

`September 2017-September 2019`
__Full-Time Volunteer Representative__
_The Church of Jesus Christ of Latter-Day Saints_
-   Coordinated efforts of groups of 5-25 volunteers over many cities
-   Conducted regular 30 minute to one-hour trainings including counsel setting meetings

__Eagle Scout__

## Skills & Interests

-   Knowledgeable in: Excel VBA, Power BI, Tableau, QuickBooks Online
-   Interests: fly fishing, football, skiing, hiking


<!-- ### Footer

Last updated: July 2024 -->